### ISSUE TITLE
create "Taxi" TO

### ISSUE THREAD

**Issue by stephanroosli** [TOMP-WG/TOMP-REF#13]
extend the list of current providers with that of a "taxi" TO

**Comment by edwinvandenbelt** [comment]
What's the scenario:
1) just "I'm here and I want to go to location B" (the normal way of accessing taxi's)
2) reserve taxi's (in this case the physical addresses should be provided)?

When should the taxi firm accept a request (startpoint in certain area, start & endpoint within certain area, ...)?
Should the taxi driver start & end the trip?
Should the taxi driver request direct payment at the end of the trip?

**Comment by stephanroosli** [comment]
I didn't manage to code proper "behaviour" into this Taxi TO. It was mainly meant to understand the code, and create my own version of a TO.  The PR was only meant to go into my personal repo, but not in the main one? You can disregard the code bit. The issue still stands.

The issue here still stands though.

I think the scenarios should be similar to what we can expect with the integration of FMS. So more details need to be figured out.

**Comment by edwinvandenbelt** [comment]
"FMS" is available as TO, with postponed commit and the postponed trips are available on a website.
